### ISSUE TITLE
mapPartitions

### ISSUE THREAD

**Issue by elenacuoco** [JoeriHermans/dist-keras#2]
I found the following error while trying to run your example 
```
Traceback (most recent call last):
  File "/home/dist-keras/examples/single_trainer_example.py", line 78, in <module>
    dataset = labelVectorTransformer.transform(dataset).toDF().select("features_normalized", "label_index", "label")
  File "/home/dist-keras/distkeras/distributed.py", line 54, in transform
    return data.mapPartitions(self._transform)
  File "/home/spark/python/pyspark/sql/dataframe.py", line 844, in __getattr__
    "'%s' object has no attribute '%s'" % (self.__class__.__name__, name))
AttributeError: 'DataFrame' object has no attribute 'mapPartitions'
 

```

**Comment by JoeriHermans** [comment]
Which example are you running exactly?

**Comment by elenacuoco** [comment]
Thanks!

**Comment by JoeriHermans** [comment]
Hi @elenacuoco 

Can you confirm if it works for you now? I pushed the changes to the master branch.

**Comment by elenacuoco** [comment]
Now I found this error
from distkeras.distributed import DPGO
ImportError: cannot import name DPGO

Maybe is my local problem. I will check better tomorrow morning

**Comment by JoeriHermans** [comment]
No, it is a problem on my side, I removed DPGO in the development branched. Sorry for the inconvenience. Need to check my commits better. Sorry. I'll fix it tomorrow.

**Comment by elenacuoco** [comment]
Hi,
I run again following the code lines for single trainer and I found now
 model = trainer.train(trainingSet)
  File "build/bdist.linux-x86_64/egg/distkeras/distributed.py", line 147, in train
NameError: global name 'SingleTrainerWorker' is not defined

**Comment by JoeriHermans** [comment]
Ok, it is fixed now. I accidentally removed that worker when removing DPGO.
